import core.ColorSpec;
import core.DetailLevel;
import core.ModelAnalysis;
import core.ModelSpec;
import core.PartSpec;
import core.CubeSpec;
import core.PoseSpec;
import core.TextureAtlas;
import modeldefs.ExampleModelDef;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

/**
 * Entry point and orchestrator for the Forge model generator.
 *
 * <h3>What this class does</h3>
 * <ol>
 *   <li>Selects a model definition from {@code modeldefs/}.</li>
 *   <li>Calls its {@code build(DetailLevel)} method to obtain a {@link ModelSpec}.</li>
 *   <li>Validates and analyses the spec.</li>
 *   <li>Generates Java source code (a Forge {@code EntityModel} subclass) into
 *       {@code src/generated/}.</li>
 *   <li>Generates a texture atlas PNG into {@code src/generated/} when enabled.</li>
 * </ol>
 *
 * <h3>How to add a new model</h3>
 * <ol>
 *   <li>Create a new class in {@code src/modeldefs/} (e.g. {@code DemonModelDef.java}).</li>
 *   <li>Implement {@code public static ModelSpec build(DetailLevel detail)}.</li>
 *   <li>Call that method here and pass the result to {@link #generateJavaSource} and
 *       {@link #generateTextureAtlas}.</li>
 * </ol>
 */
public final class ForgeModelGenerator {

    /** Root output directory for all generated files. */
    private static final String OUTPUT_DIR = "src/generated";

    /** Whether to also write a texture atlas PNG alongside the Java source. */
    private static final boolean GENERATE_ATLAS = true;

    private ForgeModelGenerator() {}

    // -----------------------------------------------------------------------
    // Entry point
    // -----------------------------------------------------------------------

    public static void main(String[] args) {

        System.out.println("=== ForgeModelGenerator ===");

        // 1. Choose detail level (can be driven from args in the future)
        DetailLevel detail = DetailLevel.MEDIUM;

        // 2. Build model specification from the chosen definition
        ModelSpec spec = ExampleModelDef.build(detail);
        System.out.println("Built spec: " + spec);

        // 3. Validate and print analysis summary
        ModelAnalysis.validate(spec);
        System.out.println(ModelAnalysis.summarise(spec));

        // 4. Generate Java source
        try {
            generateJavaSource(spec);
        } catch (IOException e) {
            System.err.println("ERROR generating Java source: " + e.getMessage());
            System.exit(1);
        }

        // 5. Optionally generate texture atlas PNG
        if (GENERATE_ATLAS) {
            try {
                generateTextureAtlas(spec);
            } catch (IOException e) {
                System.err.println("ERROR generating texture atlas: " + e.getMessage());
                System.exit(1);
            }
        }

        System.out.println("Done. Generated files are in: " + OUTPUT_DIR);
    }

    // -----------------------------------------------------------------------
    // Java source generation
    // -----------------------------------------------------------------------

    /**
     * Generates a Forge-compatible {@code EntityModel} Java source file from a
     * {@link ModelSpec} and writes it into {@link #OUTPUT_DIR}.
     *
     * @param spec the model specification to render
     * @throws IOException if the file cannot be written
     */
    static void generateJavaSource(ModelSpec spec) throws IOException {
        String className = spec.getName() + "Model";
        String fileName  = className + ".java";
        File   outFile   = new File(OUTPUT_DIR, fileName);

        ensureDirectory(OUTPUT_DIR);

        try (PrintWriter pw = new PrintWriter(outFile, "UTF-8")) {
            writeJavaSource(pw, spec, className);
        }

        System.out.println("Generated Java source : " + outFile.getPath());
    }

    /** Writes the complete Java source to the given writer. */
    private static void writeJavaSource(PrintWriter pw, ModelSpec spec, String className) {
        pw.println("// -----------------------------------------------------------------------");
        pw.println("// Generated by ForgeModelGenerator — do not edit by hand.");
        pw.println("// Model     : " + spec.getName());
        pw.println("// Detail    : " + spec.getDetailLevel());
        pw.println("// Parts     : " + ModelAnalysis.countParts(spec));
        pw.println("// Cubes     : " + ModelAnalysis.countCubes(spec));
        pw.println("// -----------------------------------------------------------------------");
        pw.println();
        pw.println("import com.mojang.blaze3d.vertex.PoseStack;");
        pw.println("import net.minecraft.client.model.EntityModel;");
        pw.println("import net.minecraft.client.model.geom.ModelPart;");
        pw.println("import net.minecraft.client.model.geom.PartPose;");
        pw.println("import net.minecraft.client.model.geom.builders.CubeListBuilder;");
        pw.println("import net.minecraft.client.model.geom.builders.LayerDefinition;");
        pw.println("import net.minecraft.client.model.geom.builders.MeshDefinition;");
        pw.println("import net.minecraft.client.model.geom.builders.PartDefinition;");
        pw.println("import net.minecraft.world.entity.Entity;");
        pw.println();
        pw.println("public class " + className + " extends EntityModel<Entity> {");
        pw.println();

        // Field declarations
        List<PartSpec> rootParts = spec.getRootParts();
        for (PartSpec part : rootParts) {
            pw.println("    private final ModelPart " + part.getName() + ";");
        }
        pw.println();

        // Constructor
        pw.println("    public " + className + "(ModelPart root) {");
        for (PartSpec part : rootParts) {
            pw.println("        this." + part.getName()
                     + " = root.getChild(\"" + part.getName() + "\");");
        }
        pw.println("    }");
        pw.println();

        // createBodyLayer()
        pw.println("    public static LayerDefinition createBodyLayer() {");
        pw.println("        MeshDefinition mesh = new MeshDefinition();");
        pw.println("        PartDefinition root = mesh.getRoot();");
        pw.println();

        for (PartSpec part : rootParts) {
            writePartDefinition(pw, "root", part);
            pw.println();
        }

        pw.println("        return LayerDefinition.create(mesh, "
                 + spec.getTextureWidth() + ", " + spec.getTextureHeight() + ");");
        pw.println("    }");
        pw.println();

        // setupAnim() — minimal no-op implementation
        pw.println("    @Override");
        pw.println("    public void setupAnim(Entity entity, float limbSwing, float limbSwingAmount,");
        pw.println("                         float ageInTicks, float netHeadYaw, float headPitch) {");
        pw.println("        // Animation logic goes here");
        pw.println("    }");
        pw.println();

        // renderToBuffer()
        pw.println("    @Override");
        pw.println("    public void renderToBuffer(PoseStack poseStack,");
        pw.println("                               com.mojang.blaze3d.vertex.VertexConsumer buffer,");
        pw.println("                               int packedLight, int packedOverlay,");
        pw.println("                               float red, float green, float blue, float alpha) {");
        for (PartSpec part : rootParts) {
            pw.println("        " + part.getName()
                     + ".render(poseStack, buffer, packedLight, packedOverlay, "
                     + "red, green, blue, alpha);");
        }
        pw.println("    }");
        pw.println("}");
    }

    /**
     * Recursively writes a {@code PartDefinition} block for the given part.
     *
     * @param pw     output writer
     * @param parent variable name of the parent ({@code "root"} for top-level parts)
     * @param part   part to emit
     */
    private static void writePartDefinition(PrintWriter pw, String parent, PartSpec part) {
        String varName = part.getName().replace(' ', '_');

        // Build the CubeListBuilder chain
        StringBuilder cubeChain = new StringBuilder("CubeListBuilder.create()");
        for (CubeSpec cube : part.getCubes()) {
            cubeChain.append(String.format(
                "%n            .texOffs(%d, %d).addBox(%sf, %sf, %sf, %sf, %sf, %sf)",
                cube.getU(), cube.getV(),
                fmt(cube.getX()),     fmt(cube.getY()),     fmt(cube.getZ()),
                fmt(cube.getSizeX()), fmt(cube.getSizeY()), fmt(cube.getSizeZ())));
        }

        // PartPose
        String poseExpr = buildPartPoseExpr(part);

        pw.println("        PartDefinition " + varName + " = " + parent + ".addOrReplaceChild(");
        pw.println("            \"" + part.getName() + "\",");
        pw.println("            " + cubeChain + ",");
        pw.println("            " + poseExpr + ");");

        // Recurse into children
        for (PartSpec child : part.getChildren()) {
            writePartDefinition(pw, varName, child);
        }
    }

    /** Builds the {@code PartPose.offset(...)} or {@code PartPose.offsetAndRotation(...)} call. */
    private static String buildPartPoseExpr(PartSpec part) {
        PoseSpec pose = part.getDefaultPose();
        if (pose.hasRotation()) {
            return String.format(
                "PartPose.offsetAndRotation(%sf, %sf, %sf, %sf, %sf, %sf)",
                fmt(pose.getPivotX()), fmt(pose.getPivotY()), fmt(pose.getPivotZ()),
                fmt(pose.getRotX()),   fmt(pose.getRotY()),   fmt(pose.getRotZ()));
        } else {
            return String.format(
                "PartPose.offset(%sf, %sf, %sf)",
                fmt(pose.getPivotX()), fmt(pose.getPivotY()), fmt(pose.getPivotZ()));
        }
    }

    // -----------------------------------------------------------------------
    // Texture atlas generation
    // -----------------------------------------------------------------------

    /**
     * Allocates UV regions for every part in the model, fills them with a distinct
     * tint, and writes the resulting atlas PNG into {@link #OUTPUT_DIR}.
     *
     * @param spec the model specification
     * @throws IOException if the PNG cannot be written
     */
    static void generateTextureAtlas(ModelSpec spec) throws IOException {
        TextureAtlas atlas = spec.getTextureAtlas();

        // Allocate a region per root part (simple demonstration — a full
        // implementation would allocate per cube-face)
        // Compute hue step. ModelAnalysis.validate() (called above) guarantees
        // at least one root part exists, so getRootParts().size() is always >= 1.
        float hueStep = (spec.getRootParts().size() > 1)
            ? 1f / spec.getRootParts().size()
            : 0.5f;
        float hue = 0f;

        for (PartSpec part : spec.getRootParts()) {
            allocatePartRegion(atlas, part, hue);
            hue += hueStep;
        }

        String pngPath = OUTPUT_DIR + "/" + spec.getName().toLowerCase() + "_texture.png";
        atlas.writePNG(pngPath);
        System.out.println("Generated texture atlas : " + pngPath);
    }

    /**
     * Allocates and fills atlas regions for all cubes in a part (and its children).
     *
     * @param atlas  the texture atlas
     * @param part   the part to process
     * @param hue    a hue value [0,1] used to tint this part's region
     */
    private static void allocatePartRegion(TextureAtlas atlas, PartSpec part, float hue) {
        for (CubeSpec cube : part.getCubes()) {
            int regionW = (int) (2 * (cube.getSizeZ() + cube.getSizeX()));
            int regionH = (int) (cube.getSizeZ() + cube.getSizeY());
            regionW = Math.max(1, regionW);
            regionH = Math.max(1, regionH);

            ColorSpec fill = hsvToColor(hue, 0.6f, 0.85f);
            TextureAtlas.Region region = atlas.allocate(part.getName(), regionW, regionH, fill);
            atlas.drawBorder(region, ColorSpec.BLACK);
        }

        for (PartSpec child : part.getChildren()) {
            allocatePartRegion(atlas, child, hue);
        }
    }

    // -----------------------------------------------------------------------
    // Utilities
    // -----------------------------------------------------------------------

    /** Ensures the output directory exists, creating it (and parents) if necessary. */
    private static void ensureDirectory(String path) throws IOException {
        File dir = new File(path);
        if (!dir.exists()) {
            if (!dir.mkdirs()) {
                throw new IOException("Could not create output directory: " + dir.getAbsolutePath());
            }
        }
    }

    /**
     * Formats a float value for use in generated Java source.
     * Integer values are formatted without a decimal point (e.g. {@code "4"}),
     * non-integer values use one decimal place (e.g. {@code "4.5"}).
     */
    private static String fmt(float f) {
        if (f == (int) f) return String.valueOf((int) f);
        return String.format("%.1f", f);
    }

    /**
     * Converts an HSV color (all channels in [0,1]) to a {@link ColorSpec}.
     * Uses the standard 6-sector HSV → RGB algorithm.
     */
    private static ColorSpec hsvToColor(float h, float s, float v) {
        float r, g, b;
        if (s == 0f) {
            r = g = b = v;
        } else {
            float sector = h * 6f;
            int   i = (int) sector;
            float f = sector - i;
            float p = v * (1 - s);
            float q = v * (1 - s * f);
            float t = v * (1 - s * (1 - f));
            switch (i % 6) {
                case 0:  r = v; g = t; b = p; break;
                case 1:  r = q; g = v; b = p; break;
                case 2:  r = p; g = v; b = t; break;
                case 3:  r = p; g = q; b = v; break;
                case 4:  r = t; g = p; b = v; break;
                default: r = v; g = p; b = q; break;
            }
        }
        return new ColorSpec(r, g, b);
    }
}
